on: [push]

jobs:
  notify:
    runs-on: alpine
    steps:
      - name: Install deps
        run: apk add --no-cache curl

      - name: Trigger build
        run: >-
          curl -X POST
          -H "Authorization: token ${{ secrets.TOKEN }}"
          -H "Accept: application/json"
          http://forgejo:3000/api/v1/repos/nnra6864/quartz-Vault/dispatches
          -d '{"type": "notes_updated"}'
