on: [push]

jobs:
  notify:
    runs-on: alpine
    steps:
      - name: Install deps
        run: apk add --no-cache curl

      - name: Trigger build
        run: >-
          curl -X POST "http://forgejo:3000/api/v1/repos/nnra6864/quartz-Vault/actions/workflows/build.yaml/dispatches"
          -H "Authorization: token ${{ secrets.TOKEN }}"
          -H "Content-Type: application/json"
          -d '{ "ref": "v5", "inputs": {} }'

