on: [push]

jobs:
  notify:
    runs-on: build-alpine
    steps:
      - name: Trigger Quartz Build
      - run: apk add --no-cache curl
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.TOKEN }}" \
            -H "Accept: application/json" \
            "https://git.nnstdios.xyz/api/v1/repos/nnra6864/quartz-Notes/dispatch" \
            -d '{"event_type": "notes_updated"}'
